spring:
  application:
    name: cloud-service

server:
  port: 8010

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    appname: cloud-service-1
    prefer-ip-address: true
    app-group-name: cloud

